issues:
  exclude-dirs:
    - .git
    - vendor
    - bin
    - tmp
    - testdata
  max-issues-per-linter: 0  # Ноль допущенных ошибок
  max-same-issues: 0

linters-settings:
  depguard:
    list-type: whitelist
    packages:
      - std  # Стандартная библиотека
      
      # Разрешённые внешние зависимости (явно с версиями)
      - github.com/labstack/echo/v4@v4.11.4
      - gorm.io/gorm@v1.25.*
      - github.com/google/uuid@v1.4.0
      
      # Внутренние пакеты
      - POSTnGETtrain/internal/...
      
    reject-packages:
      - github.com/old/unsafe-pkg  # Явный запрет опасных пакетов
    include-go-root: true

  revive:
    rules:
      - name: package-comments
        severity: error  # Обязательные комментарии к пакетам
      - name: exported
        severity: error  # Требует docstring для экспортируемых сущностей
      - name: cognitive-complexity
        arguments: [7]  # Максимальная сложность функций
        severity: error

  gocyclo:
    min-complexity: 10  # Флаги для сложных функций

  gosec:
    excludes:
      - G104  # errcheck уже обрабатывает непроверенные ошибки
    config:
      global:
        # Запрещённые функции
        forbidden-functions:
          - exec.Command: "Use безопасные альтернативы из пакета safexec"
          - fmt.Printf: "Используйте логгер"

linters:
  enable:
    # Базовые
    - govet
    - staticcheck
    - errcheck
    - unused
    
    # Стиль и сложность
    - revive
    - gocyclo
    - gocritic
    - nestif
    
    # Безопасность
    - gosec
    - forbidigo
    
    # Производительность
    - prealloc
    - wastedassign
    
    # Дополнительные проверки
    - bodyclose
    - noctx
  disable-all: true

run:
  timeout: 5m  # Увеличенный таймаут для больших проектов
  tests: false  # Отключить проверку тестов (если нужно)